# Basic
title: context dependent
author: thomas mcmanus
description: this is a bad blog

url: "https://context-dependent.github.io"

permalink: /:year/:month/:title/

# Format
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    github: context-dependent
    mail: tomas.k.mcmanus@gmail.com
